cache:
  paths:
  - app/vendor/

stages:
  - build
  - deploy

build:
  stage: build
  script:
  - yes | docker network prune
  - docker-compose build

deploy:
  stage: deploy
  script:
  - docker-compose down --remove-orphans
  - docker-compose up -d
