version: "3"
services:
  app:
    build: .
    ports:
      - "4563:4941"
    environment:
      - SENG365_MYSQL_HOST
      - SENG365_MYSQL_PORT
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
  mysql:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
